substitutions:
  name: "New athom device"
  project_version: "1.1"

packages:
  common: !include ../common.yaml

esphome:
  name: "${name}"
  name_add_mac_suffix: false
  project:
    name: "${project_name}"
    version: "${project_version}"
  platformio_options:
    board_upload.flash_size: 2MB
    board_upload.maximum_size: 2097152
    board_build.ldscript: eagle.flash.2m.ld

esp8266:
  board: esp8285
  restore_from_flash: false

api:
