# https://github.com/athom-tech/athom-configs/blob/main/athom-smart-plug-v2.yaml
substitutions:
  project_name: "athom.smart-plug"
  button_pin: GPIO5
  button_mode: INPUT_PULLUP
  output_pin: GPIO12

packages:
  common: !include common.yaml
  power: !include power/power.yaml

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

light:
  - platform: status_led
    name: "${name} LED"
    id: led_status
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO13

sensor:
  - platform: uptime
    name: "${name} Uptime"
    disabled_by_default: true

  - platform: cse7766
    current:
      name: "${name} Current"
      id: current
      unit_of_measurement: A
      accuracy_decimals: 2
      filters:
        - throttle_average: 10s
        - lambda: if (x < 0.060) return 0.0; else return x; #For the chip will report less than 3w power when no load is connected
      on_value_range:
        - above: 16
          then:
            - switch.turn_off: relay
    voltage:
      name: "${name} Voltage"
      id: voltage
      unit_of_measurement: V
      accuracy_decimals: 1
      filters:
        - throttle_average: 10s

    power:
      name: "${name} Power"
      id: socket_my_power
      unit_of_measurement: W
      accuracy_decimals: 1
      filters:
        - throttle_average: 10s
        - lambda: if (x < 3.0) return 0.0; else return x; #For the chip will report less than 3w power when no load is connected

  - platform: total_daily_energy
    name: "${name} Total Energy"
    power_id: socket_my_power
    unit_of_measurement: kWh
    icon: mdi:hours-24
    accuracy_decimals: 3
    restore: true
    filters:
      - multiply: 0.001

script:
  - id: after_double_click
    then:
      - delay: 2s

  - id: after_long_press
    then:
      - delay: 2s

  - id: after_on
    then:
      - light.turn_on: led_status

  - id: after_off
    then:
      - light.turn_off: led_status
