substitutions:
  restore_mode: RESTORE_DEFAULT_OFF
  relay_id: relay

switch:
  - platform: output
    id: relay
    name: "${name}"
    output: output_relay
    restore_mode: ${restore_mode}
    on_turn_on:
      - script.execute: after_on
    on_turn_off:
      - script.execute: after_off
